services:
  # 1. Base de Datos
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      # Mapeamos tus variables a las que exige la imagen de Postgres
      POSTGRES_USER: ${DB_USER}         # Lee del .env
      POSTGRES_PASSWORD: ${DB_PASSWORD} # Lee del .env
      POSTGRES_DB: ${DB_NAME}           # Lee del .env
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Backend Go
  backend:
    build: .
    container_name: torque_backend
    volumes:
      - .:/app
    working_dir: /app/backend
    ports:
      - "${WEB_PORT}:8080"
    depends_on:
      - db
    # MÃ¡gia: Docker inyecta TODAS las variables del .env dentro del contenedor de Go
    env_file:
      - .env 
    command: ["tail", "-f", "/dev/null"]

volumes:
  postgres_data:
